#!/bin/bash
# Usage: Hello World Bash Shell Script Using Variables
# Author: Ruheena Parveen
# -------------------------------------------------
# Define bash shell variable called var 
# Avoid spaces around the assignment operator (=)
test="Hello World"
# print it 
echo "$test"
# Another way of printing it
printf "%s\n" "$test"
